name = "clanker-fm"
compatibility_date = "2025-09-01"

[build]
# Use the Next-on-Pages wrapper instead of `next build`
command = "npm run cf-build"
pages_build_output_dir = ".vercel_build_output/output"
pages_functions_dir    = ".vercel_build_output/functions"